version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/home/moodle/mariadb-persistence:/bitnami'
  moodle:
    image: 'bitnami/moodle:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/home/moodle/moodle-persistence:/bitnami'
    depends_on:
      - mariadb
